espanso/hub

- packages/caron-letters/0.1.0/README.md
- packages/caron-letters/0.1.0/_manifest.yml
- packages/caron-letters/0.1.0/package.yml
The package could be expanded in the future by adding the rest of the caron letters available in other languages, as it currently supporting only the ones present in the Slovenian language.
> Add caron-letters package

- packages/translate-fr-en/0.1.0/LICENSE
- packages/translate-fr-en/0.1.0/README.md
- packages/translate-fr-en/0.1.0/_manifest.yml
This is a proof-of-concept translation package. I believe this is the first Espanso package to help with translation.
My goal is to improve people's fluency and language-learning ability when having text-based conversations. I found that text-expansion is a great tool that lets people find words they need, without getting distracted by a dictionary.
I generated the bidirectional translation trigger/replacement package.yml file at 
[espanso-translate-fr-en-generator](https://github.com/IdiosApps/espanso-translate-fr-en-generator).
The package is just under 10MB, and Espanso uses about 350MB of memory when it is loaded in. Whilst it is quite large, the package readme states this and so it's up to users if they want to try it. I didn't make any optimisations - it's just a POC at the moment. …
> Add English-French translation package

- packages/calc/1.0.0/README.md
- packages/calc/1.0.0/_manifest.yml
- packages/calc/1.0.0/package.yml
after I install the new version of Espanso, calc package version 0.1.0 have not run because of Espanso's new syntax role.
I changed the syntax {{val}} to [[val]]
> style: match new version of espanso syntax for calc package

- .github/workflows/pr-quality-check.yml
The comment isn't really useful, as you need to enter the Actions section anyway to read it
> :fire: remove posting comment section in CI

- packages/lean/0.1.0/README.md
- packages/lean/0.1.0/_manifest.yml
- packages/lean/0.1.0/package.yml
This PR adds a package for the Unicode abbreviations used by the [editor](https://github.com/leanprover/vscode-lean4) [plugins](https://github.com/Julian/lean.nvim) for the [Lean theorem prover](https://leanprover.github.io/).
> New package: Lean

- packages/sitelen-pona/0.1.0/README.md
- packages/sitelen-pona/0.1.0/_manifest.yml
- packages/sitelen-pona/0.1.0/package.yml
Added package for typing sitelen pona (toki pona's main writing system) via UCSUR.
If you're wondering, the language at the end of the readme is [toki pona](https://tokipona.org/), and what I wrote translates to about:
> Using this tool, you can write sitelen pona with Espanso. Communicate/talk well and write well!
> Add sitelen-pona package

- packages/air-codes/0.1.0/LICENSE
- packages/air-codes/0.1.0/README.md
- packages/air-codes/0.1.0/_manifest.yml
- packages/air-codes/0.1.0/package.yml
Hello,
I would like to submit a package I have created to the Espanso hub.
This package is related to airports and airlines.
The **air-codes** package can become a resource for air transportation data, offering convenient access to:
- Properly formatted airport names and locations based on their IATA codes.
- Accurate airline names associated with their respective IATA 2-letter airline identifiers.
Don't hesitate to review the _readme.md_ file for further information.
If needed, don't hesitate to contact me.
Thank you.
> New "air-codes" espanso package

- packages/quick-translate/0.1.0/README.md
- packages/quick-translate/0.1.0/_manifest.yml
- packages/quick-translate/0.1.0/defaultlang.yml
- packages/quick-translate/0.1.0/package.yml
This expansion uses the [translate-shell](https://github.com/soimort/translate-shell) CLI-tool to do in-line translations from and to many languages. The default source and target languages of the user can be defined within `defaultlang.yml` as this file serves as the global variable definition of them
> Add quick-translate Package to translate between many languages using translate-shell

- packages/python-utils/0.1.0/README.md
- packages/python-utils/0.1.0/_manifest.yml
- packages/python-utils/0.1.0/package.yml
Some shortcuts to reduce the amount of boilerplate code for python scripts.
> Add `python-utils` package

- packages/calc-macos/0.1.1/README.md
- packages/calc-macos/0.1.1/_manifest.yml
- packages/calc-macos/0.1.1/package.yml
Version number updated to cause the hub to pick up the package. 
README.md already amended with a missing `</img>` tag added.
> New version of calc-macos

- README.md
> :memo: add Contributing section

- packages/discord-snippet/0.1.0/README.md
- packages/discord-snippet/0.1.0/_manifest.yml
Hi,
It's me again
It's appear that the hub page for my package is blank.
I suppose it's the missing "" for the link in HomePage.
> Blank Page For Discord-Snippets in Hubs

- packages/oasis-is-framework/0.1.0/README.md
- packages/oasis-is-framework/0.1.0/_manifest.yml
- packages/oasis-is-framework/0.1.0/package.yml
This is a mega-prompt framework form for prompting in ChatGPT, Claude and other chatbots.  It has two modes.  
1.  Using it in a URL bar or any text field it creates a prompt that will run in chatGPT.  This is the base version that allows users to get the full prompt in the form of a URL. This only works for ChatGPT.
2. This is meant to be used in any prompt box.  It does not include the URL, but just the text for the prompt.
> Created a new Package for espanso - OASIS-IS Prompt Framework

- packages/linter-control-comments/0.1.0/README.md
- packages/linter-control-comments/0.1.0/_manifest.yml
- packages/linter-control-comments/0.1.0/package.yml
This is intended to provide editor-independent access to comments like `# rubocop:disable …`, `//nolint:…` etc. in order to control linter behaviour in source code files.
They make heavy use of the `{clipboard}`, into which one can copy a particular linting rule name (from docs, terminal output, etc.) before triggering the espansion.
Would this be a useful addition here?
*PS: The specific snippets are just a rough start. Not necessarily complete with respect to what their respective docs list as available, nor based on any analysis of real-world usage.*
> Add package `linter-control-comments` (Golint, Rubocop/Ruby, Clippy/Rust and Shellcheck)

- packages/jekyll-yaml/0.1.0/README.md
- packages/jekyll-yaml/0.1.0/_manifest.yml
- packages/jekyll-yaml/0.1.0/package.yml
Nothing much but I use the command nearly every day. Thought some other users may like it. Makes writing in an editor like iA writer much easier.
> Small Jekyll YAML Metadata package

- packages/dummy-package/0.1.0/_manifest.yml
Follow-up to https://github.com/espanso/hub/pull/132#issuecomment-2408869971 as per:
> … we've had problems merging some packages where this is omitted
Should it be moved into the mandatory list in [package-specification.md@website](https://github.com/espanso/website/blob/7ff68ce0f81abe51fac1a13d66d21ff1b8286df1/docs/packages/package-specification.md#the-_manifestyml-file) as well?
> Add homepage field to pkg template

- packages/form-list/0.2.0/README.md
- packages/form-list/0.2.0/_manifest.yml
- packages/form-list/0.2.0/form_urls.csv
- packages/form-list/0.2.0/package.yml
Much amended version of part of the failed PR https://github.com/espanso/hub/pull/87. 
It's been over a year since the original submission and I have been unable to get a response from @mistahBen, even going as far as submitting a PR https://github.com/mistahBen/espanso_hub/pull/1 to his own repo, with corrected code.
I like this package as it illustrates a useful technique, so I think it's worth preserving. 
I'll close #87.
Thanks to @mistahBen for the idea!
> Form URL list

- packages/form-list/0.2.1/README.md
- packages/form-list/0.2.1/_manifest.yml
- packages/form-list/0.2.1/form_urls.csv
- packages/form-list/0.2.1/package.yml
Removed "`0.2.0,"` from line 14 of `package.yml`.
`_manifest.yml` updated to new version.
> Minor mistake corrected

- packages/date-offset/0.1.0/README.md
- packages/date-offset/0.1.0/_manifest.yml
- packages/date-offset/0.1.0/package.yml
- packages/timezone-date/0.1.0/README.md
- packages/timezone-date/0.1.0/_manifest.yml
- packages/timezone-date/0.1.0/_package.yml
- packages/timezone-date/0.1.0/package.yml
#139 related.
Both packages contain benign, date-handling scripts in several scripting languages.
> New date packages, `date-offset` and `timezone-date`

- packages/tailwindcss-colors/0.1.1/README.md
- packages/tailwindcss-colors/0.1.1/_manifest.yml
- packages/tailwindcss-colors/0.1.1/package.yml
This update resolves an issue where color triggers were unintentionally activated by partial matches, causing incorrect values to be inserted.
To address this, word triggers are now used for all colors, ensuring each trigger is distinct and only activated when surrounded by word separators (e.g., spaces, commas, or newlines).
For instance, typing `:slate500` previously triggered `:slate50` because it was a substring. This behavior has now been fixed.
> Update `tailwindcss-colors` package -> 0.1.1

- packages/delays-characters/0.1.0/README.md
- packages/delays-characters/0.1.0/_manifest.yml
- packages/delays-characters/0.1.0/package.yml
- packages/delays-characters/0.1.0/parse_pynput.py
An Espanso trigger that uses the Python `pynput` library to inject text, *instead* of Espanso. This enables the addition of pauses (sleep), \<Tab> etc, and other key combinations not supported by Espanso.
> Add delays-characters package

- packages/base64-encoder-decoder/0.1.0/README.md
- packages/base64-encoder-decoder/0.1.0/_manifest.yml
Hello friends! In this adjustment, I just fixed an issue with the repository link that was incorrect in the manifest and also a small adjustment in the package description in readme.md
> `base64-encoder-decoder` Minor Description and Manifest changes.

- packages/verbose-form-template/1.0.1/README.md
- packages/verbose-form-template/1.0.1/_manifest.yml
- packages/verbose-form-template/1.0.1/package.yml
I liked what the original package could do, but following an initial dialogue with the author, we were still left with various issues in the original PR https://github.com/espanso/hub/pull/85/files#diff-e9a373201f8cc15904a47996833a6560bd9c676535441158e0cf832b61f2f309
I decided to rework it and:
- removed the original package whose name was prefixed with 'espanso-'
- rewritten `README.md` to replace the emphasis on `choice` in favour of `list`
- removed the image from the package
- updated `_manifest.yml` with corrected `name:`, `homepage:`, `title:`, and added my name as a contributor
- reformatted `package.yml` to make it more readable, shortened the trigger, and reformatted the form so it displays better and is easier to use.
I submitted a PR to the author's repo three months ago, but …
> Reworking of verbose-form-template package

- packages/star-rating/0.1.1/LICENSE
- packages/star-rating/0.1.1/README.md
- packages/star-rating/0.1.1/_manifest.yml
- packages/star-rating/0.1.1/package.yml
The version in the [Hub](https://hub.espanso.org/star-rating) doesn't have a `matches:` line at the top.
It _is_ present in the [repo](https://github.com/espanso/hub/blob/main/packages/star-rating/0.1.0/package.yml), although not the original [PR](https://github.com/espanso/hub/pull/157).
This is an attempt to correct the problem by pushing an updated version.
> No 'matches:` line in `package.yml`
