- packages/accented-words/1.0.0/LICENSE
- packages/accented-words/1.0.0/README.md
- packages/accented-words/1.0.0/_manifest.yml
- packages/accented-words/1.0.0/package.yml
Added a simple package for commonly accented words in English.  Let me know if you have any questions, comments, or concerns.
> Add accented words package

- packages/hugo-shortcodes/0.1.0/README.md
- packages/hugo-shortcodes/0.1.0/_manifest.yml
- packages/hugo-shortcodes/0.1.0/package.yml
hugo-shortcodes adds triggers for the static site generator Hugo.
> Initial commit.

- packages/hax/0.1.0/README.md
- packages/hax/0.1.0/_manifest.yml
- packages/hax/0.1.0/package.yml
It includes replacements for payloads in a multitude of attack types and general utility replacements. I found this handy and incorporated it in my workflow and am sharing it in hope that others find it useful, too! :)
> Added package 'Hax' which includes replacements and snippets for hackers and penetration testers

- packages/drug-names/0.1.0/README.md
- packages/drug-names/0.1.0/_manifest.yml
- packages/drug-names/0.1.0/package.yml
I'm new at this but I believe I've followed the instructions correctly. I'm really excited to contribute to this fantastic tool!
> Drug Name Expansions

- packages/foreign-thanks/1.1.0/LICENSE
- packages/foreign-thanks/1.1.0/README.md
- packages/foreign-thanks/1.1.0/_manifest.yml
- packages/foreign-thanks/1.1.0/package.yml
Add new updated version (1.1.0) of foreign-thanks package
> Update `foreign-thanks` package

- packages/typofixer-en/1.0.0/README.md
- packages/typofixer-en/1.0.0/_manifest.yml
- packages/typofixer-en/1.0.0/package.yml
- packages/typofixer-es/1.0.0/README.md
- packages/typofixer-es/1.0.0/_manifest.yml
- packages/typofixer-es/1.0.0/package.yml
- packages/typofixer-fr/1.0.0/README.md
- packages/typofixer-fr/1.0.0/_manifest.yml
- packages/typofixer-fr/1.0.0/package.yml
- packages/typofixer-it/1.0.0/README.md
- packages/typofixer-it/1.0.0/_manifest.yml
- packages/typofixer-it/1.0.0/package.yml
Ref: https://github.com/Mte90/espanso-typofixer
> Typofixer package for 4 languages

- packages/rand-tools/0.0.2/README.md
- packages/rand-tools/0.0.2/_manifest.yml
- packages/rand-tools/0.0.2/package.yml
This is a package that generates random strings with a length that could be customized by the users, based on the `openssl rand` command, aimed at use cases such as username and password generation.
For more information, please read the README.md file.
> Random String Generation Package

- packages/kubernetes/0.1.0/README.md
- packages/kubernetes/0.1.0/_manifest.yml
- packages/kubernetes/0.1.0/package.yml
Hi, 
There is a package on k8s (specifically for commands around Kubernetes), I created a different package that creates YAML manifests for kube.
I think it's better to have one package for commands, and one for files.
> Espanso snippets for Kubernetes (Manifests)

- packages/us-time-zones/0.1.0/README.md
- packages/us-time-zones/0.1.0/_manifest.yml
- packages/us-time-zones/0.1.0/package.yml
Created package for simple US timezone conversion.
> Added us-timezones package.v0.1.0

- packages/single-steno/0.1.0/README.md
- packages/single-steno/0.1.0/_manifest.yml
- packages/single-steno/0.1.0/package.yml
Add the `single-steno` package to the package repo.
> add single-steno package

- packages/aspnetboilerplate-aspzerohub/0.1.0/README.md
- packages/aspnetboilerplate-aspzerohub/0.1.0/_manifest.yml
- packages/aspnetboilerplate-aspzerohub/0.1.0/package.yml
AspNet Boilerplate and Asp Zero Code Shortcut Added Espanso
> AspNet Boilerplate and Asp Zero Shortcut

- packages/clipboard-lower-upper-win/0.1.0/LICENSE
- packages/clipboard-lower-upper-win/0.1.0/README.md
- packages/clipboard-lower-upper-win/0.1.0/_manifest.yml
- packages/clipboard-lower-upper-win/0.1.0/package.yml
Added a package to convert clipboard content to lower and upper case in Windows
> Add clipboard-lower-upper-win package

- packages/base64-encoder-decoder/0.1.0/README.md
- packages/base64-encoder-decoder/0.1.0/_manifest.yml
- packages/base64-encoder-decoder/0.1.0/package.yml
I added a small package that adds triggers to encode and decode the clipboard using base64.
> feat: Add the base64-encoder-decoder package

- packages/discord-snippet/0.1.0/README.md
- packages/discord-snippet/0.1.0/_manifest.yml
- packages/discord-snippet/0.1.0/package.yml
This is a snippets package for Discord Markdown Formatting.
> Create a new Package for Discord Markdown Formatting

- packages/discord-snippet/0.1.0/README.md
- packages/discord-snippet/0.1.0/_manifest.yml
> Revert "Blank Page For Discord-Snippets in Hubs"

- packages/discord-snippet/0.1.1/README.md
- packages/discord-snippet/0.1.1/_manifest.yml
- packages/discord-snippet/0.1.1/package.yml
Hi,
It's me again.
Now that the page has disappeared from the website, we can try to merge the package again with all the corrections.
Hopefully it won't be a blank page this time 😄.
> Retrying the merge for the Discord Markdown formatting package

- .gitignore
- README.md
Added documentation on how to validate with python locally with a computer 🙌
> :memo: add how to validate locally

- packages/form-list/0.2.0/package.yml
I shouldn't have left the version in the path.
> Minor correction

- packages/pan-snippets/0.1.0/LICENSE
- packages/pan-snippets/0.1.0/README.md
- packages/pan-snippets/0.1.0/_manifest.yml
- packages/pan-snippets/0.1.0/package.yml
- test.txt
This PR adds the `pan-snippets` package.
These are triggers to help with troubleshooting and administering Palo Alto Networks firewalls. More info in `README.md`
> added pan-snippets package

- packages/albanian-accents/0.1.0/README.md
- packages/albanian-accents/0.1.0/_manifest.yml
- packages/albanian-accents/0.1.0/package.yml
My first try here, the configiration was already tested.
Thanks!
> * Add Albanian accented characters

- packages/translate-en-zh/0.1.0/_manifest.yml
> translate-en-zh - add homepage

- packages/typst-math-symbols/0.1.0/README.md
- packages/typst-math-symbols/0.1.0/_manifest.yml
- packages/typst-math-symbols/0.1.0/package.yml
All Typst math symbols to Unicode
> typst-math-symbols
